version: 0.2

phases:
  install:
    commands:
      - echo Installing NodeJs 12...
      - curl -sL https://deb.nodesource.com/setup_$v.x | sudo -E bash -
      - echo Installing node js
      - sudo sapt-get update
      - sudo apt-get install -y nodejs

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
