FROM node:11.15.0-alpine as build-step
WORKDIR /app
COPY package.json ./
RUN npm install
RUN npm install @angular/flex-layout@2.0.0-beta.10-4905443 --save
COPY . .
RUN npm run build

FROM nginx:1.16.0-alpine as prod-stage
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-step /app/dist/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]